# Generated by Django 5.2.12 on 2026-04-02 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefvorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('inhalt', models.BinaryField(verbose_name='DOCX-Inhalt')),
                ('ist_aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('ist_standard', models.BooleanField(default=False, help_text='Wird beim neuen Brief automatisch vorausgewaehlt.', verbose_name='Standard-Vorlage')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('pfad_kuerzel', models.CharField(blank=True, default='', help_text='Kuerzel des Formular-Pfads (z. B. HUND). Wenn gesetzt, wird diese Vorlage beim Bescheid-Generator fuer diesen Pfad angeboten.', max_length=50, verbose_name='Pfad-Kuerzel')),
                ('gruppe', models.CharField(blank=True, default='', help_text='Optionaler Gruppenname innerhalb des Pfads.', max_length=100, verbose_name='Gruppe')),
                ('default_absender_name', models.CharField(blank=True, max_length=200, verbose_name='Standard-Absender Name')),
                ('default_absender_strasse', models.CharField(blank=True, max_length=200, verbose_name='Standard-Absender Strasse')),
                ('default_absender_ort', models.CharField(blank=True, max_length=200, verbose_name='Standard-Absender PLZ/Ort')),
                ('default_absender_telefon', models.CharField(blank=True, max_length=50, verbose_name='Standard-Absender Telefon')),
                ('default_absender_email', models.CharField(blank=True, max_length=200, verbose_name='Standard-Absender E-Mail')),
                ('default_ort', models.CharField(blank=True, max_length=100, verbose_name='Standard-Ort (Datum-Zeile)')),
                ('default_grussformel', models.CharField(blank=True, max_length=200, verbose_name='Standard-Grussformel')),
                ('fusszeile_firmenname', models.CharField(blank=True, max_length=200, verbose_name='Fusszeile Firmenname')),
                ('fusszeile_telefon', models.CharField(blank=True, max_length=50, verbose_name='Fusszeile Telefon')),
                ('fusszeile_telefax', models.CharField(blank=True, max_length=50, verbose_name='Fusszeile Telefax')),
                ('fusszeile_email', models.CharField(blank=True, max_length=200, verbose_name='Fusszeile E-Mail')),
                ('fusszeile_internet', models.CharField(blank=True, max_length=200, verbose_name='Fusszeile Internet')),
                ('wopi_token', models.CharField(blank=True, default='', max_length=64, verbose_name='WOPI-Token')),
                ('wopi_token_ablauf', models.DateTimeField(blank=True, null=True, verbose_name='WOPI-Token Ablauf')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefvorlagen', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Briefvorlage',
                'verbose_name_plural': 'Briefvorlagen',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='Briefvorgang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absender_name', models.CharField(max_length=200, verbose_name='Absender Name')),
                ('absender_strasse', models.CharField(blank=True, max_length=200, verbose_name='Absender Strasse')),
                ('absender_ort', models.CharField(blank=True, max_length=200, verbose_name='Absender PLZ/Ort')),
                ('absender_telefon', models.CharField(blank=True, max_length=50, verbose_name='Absender Telefon')),
                ('absender_email', models.CharField(blank=True, max_length=200, verbose_name='Absender E-Mail')),
                ('empfaenger_name', models.CharField(max_length=200, verbose_name='Empfaenger Name')),
                ('empfaenger_zusatz', models.CharField(blank=True, max_length=200, verbose_name='Empfaenger Zusatz')),
                ('empfaenger_strasse', models.CharField(blank=True, max_length=200, verbose_name='Empfaenger Strasse')),
                ('empfaenger_plz_ort', models.CharField(blank=True, max_length=200, verbose_name='Empfaenger PLZ/Ort')),
                ('empfaenger_land', models.CharField(blank=True, max_length=200, verbose_name='Empfaenger Land')),
                ('ort', models.CharField(max_length=100, verbose_name='Ort')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('betreff', models.CharField(max_length=300, verbose_name='Betreff')),
                ('anrede', models.CharField(blank=True, max_length=200, verbose_name='Anrede')),
                ('brieftext', models.TextField(blank=True, verbose_name='Brieftext')),
                ('grussformel', models.CharField(default='Mit freundlichen Gruessen', max_length=200, verbose_name='Grussformel')),
                ('unterschrift_name', models.CharField(max_length=200, verbose_name='Unterzeichner')),
                ('unterschrift_titel', models.CharField(blank=True, max_length=200, verbose_name='Funktion/Titel')),
                ('inhalt', models.BinaryField(blank=True, null=True, verbose_name='DOCX-Inhalt')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('wopi_token', models.CharField(blank=True, default='', max_length=64, verbose_name='WOPI-Token')),
                ('wopi_token_ablauf', models.DateTimeField(blank=True, null=True, verbose_name='WOPI-Token Ablauf')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('fertig', 'Fertig'), ('archiviert', 'Archiviert')], default='entwurf', max_length=20, verbose_name='Status')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='Geaendert am')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefe', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('sitzung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefe', to='formulare.antrsitzung', verbose_name='Formular-Sitzung')),
                ('vorlage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vorgaenge', to='korrespondenz.briefvorlage', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'Briefvorgang',
                'verbose_name_plural': 'Briefvorgaenge',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
