# Generated by Django 5.2.12 on 2026-04-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korrespondenz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmendaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmenname', models.CharField(blank=True, max_length=200, verbose_name='Firmenname / Behoerde')),
                ('strasse', models.CharField(blank=True, max_length=200, verbose_name='Strasse / Hausnummer')),
                ('plz_ort', models.CharField(blank=True, max_length=100, verbose_name='PLZ / Ort')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('telefax', models.CharField(blank=True, max_length=50, verbose_name='Telefax')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='E-Mail')),
                ('internet', models.CharField(blank=True, max_length=200, verbose_name='Internet')),
                ('ort', models.CharField(blank=True, max_length=100, verbose_name='Ort (fuer Datumszeile)')),
                ('grussformel', models.CharField(blank=True, default='Mit freundlichen Gruessen', max_length=200, verbose_name='Standard-Grussformel')),
            ],
            options={
                'verbose_name': 'Firmendaten',
                'verbose_name_plural': 'Firmendaten',
            },
        ),
    ]
