# Generated by Django 5.2.12 on 2026-04-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korrespondenz', '0002_firmendaten'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefvorlage',
            name='doc_key',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='OO Doc-Key'),
        ),
    ]
