# Generated by Django 5.2.12 on 2026-04-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korrespondenz', '0003_briefvorlage_doc_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankverbindung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.SlugField(help_text="Kleinbuchstaben/Ziffern/Bindestrich, z.B. 'hauptkonto'", unique=True, verbose_name='Kürzel')),
                ('bezeichnung', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('kontoinhaber', models.CharField(blank=True, max_length=200, verbose_name='Kontoinhaber')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Bank')),
                ('reihenfolge', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Bankverbindung',
                'verbose_name_plural': 'Bankverbindungen',
                'ordering': ['reihenfolge', 'bezeichnung'],
            },
        ),
    ]
