# Generated by Django 5.2.12 on 2026-04-06 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korrespondenz', '0004_bankverbindung'),
        ('workflow', '0002_alter_workflowstep_aktion_typ'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='briefvorgang',
            name='bearbeiter_signiert_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signiert am'),
        ),
        migrations.AddField(
            model_name='briefvorgang',
            name='bearbeiter_signiert_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bearbeitete_briefe', to=settings.AUTH_USER_MODEL, verbose_name='Bearbeitet und signiert von'),
        ),
        migrations.AddField(
            model_name='briefvorgang',
            name='signiert_pdf',
            field=models.BinaryField(blank=True, null=True, verbose_name='Signiertes PDF'),
        ),
        migrations.AddField(
            model_name='briefvorgang',
            name='workflow_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefe', to='workflow.workflowtask', verbose_name='Workflow-Task'),
        ),
    ]
