# Generated by Django 6.0.3 on 2026-04-02 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntrPfad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('kategorie', models.CharField(blank=True, default='', help_text="Gruppe fuer die Uebersicht, z.B. 'Steuern', 'Lizenzen'", max_length=100, verbose_name='Kategorie')),
                ('kuerzel', models.CharField(blank=True, help_text='2-6 Grossbuchstaben fuer Vorgangsnummern, z.B. HUN', max_length=6, verbose_name='Kuerzel')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('oeffentlich', models.BooleanField(default=False, help_text='Wenn aktiv, kann dieser Pfad ohne Login ausgefuellt werden', verbose_name='Oeffentlich')),
                ('variablen_json', models.JSONField(blank=True, default=dict, help_text='Pfad-weite Berechnungsgrundlagen', verbose_name='Variablen')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_pfade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Antrags-Pfad',
                'verbose_name_plural': 'Antrags-Pfade',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AntrSchritt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('felder_json', models.JSONField(default=list, help_text='Eingabefelder dieses Schritts im Schema-Format', verbose_name='Felder')),
                ('ist_ende', models.BooleanField(default=False, verbose_name='End-Knoten')),
                ('ist_start', models.BooleanField(default=False, verbose_name='Start-Knoten')),
                ('node_id', models.CharField(max_length=50, verbose_name='Node-ID')),
                ('pos_x', models.FloatField(default=200, verbose_name='Position X')),
                ('pos_y', models.FloatField(default=200, verbose_name='Position Y')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('pfad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schritte', to='formulare.antrpfad')),
            ],
            options={
                'verbose_name': 'Antrags-Schritt',
                'verbose_name_plural': 'Antrags-Schritte',
                'ordering': ['pk'],
                'unique_together': {('pfad', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='AntrSitzung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('besuchte_schritte', models.JSONField(default=list, verbose_name='Besuchte Schritte')),
                ('einwilligungen_json', models.JSONField(default=dict, help_text='Protokoll erteilter Einwilligungen mit Zeitstempel', verbose_name='Einwilligungen (DSGVO)')),
                ('email_anonym', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail (anonym)')),
                ('gesammelte_daten', models.JSONField(default=dict, verbose_name='Gesammelte Daten')),
                ('gestartet_am', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('laufend', 'Laufend'), ('abgeschlossen', 'Abgeschlossen'), ('abgebrochen', 'Abgebrochen')], default='laufend', max_length=20)),
                ('vorgangsnummer', models.CharField(blank=True, help_text='Automatisch generiert beim Abschluss, z.B. HUN-00001-20260328-1423', max_length=30, null=True, verbose_name='Vorgangsnummer')),
                ('aktueller_schritt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktive_sitzungen', to='formulare.antrschritt')),
                ('pfad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sitzungen', to='formulare.antrpfad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antr_sitzungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Antrags-Sitzung',
                'verbose_name_plural': 'Antrags-Sitzungen',
                'ordering': ['-gestartet_am'],
            },
        ),
        migrations.CreateModel(
            name='AntrDatei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateiname', models.CharField(max_length=255)),
                ('feld_id', models.CharField(max_length=100, verbose_name='Feld-ID')),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('inhalt', models.BinaryField()),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('sitzung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dateien', to='formulare.antrsitzung')),
            ],
            options={
                'verbose_name': 'Antrags-Datei',
                'verbose_name_plural': 'Antrags-Dateien',
                'ordering': ['-hochgeladen_am'],
            },
        ),
        migrations.CreateModel(
            name='AntrTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedingung', models.TextField(blank=True, help_text='Formel-Bedingung (leer = immer wahr). Referenziert Feld-IDs.', verbose_name='Bedingung')),
                ('label', models.CharField(blank=True, help_text="Optionaler Text auf der Kante, z.B. 'Ja'", max_length=100, verbose_name='Beschriftung')),
                ('reihenfolge', models.IntegerField(default=0, help_text='Auswertungsreihenfolge bei mehreren Ausgaengen (niedrig = zuerst)', verbose_name='Reihenfolge')),
                ('pfad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitionen', to='formulare.antrpfad')),
                ('von_schritt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausgaende', to='formulare.antrschritt', verbose_name='Von')),
                ('zu_schritt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eingaenge', to='formulare.antrschritt', verbose_name='Zu')),
            ],
            options={
                'verbose_name': 'Transition',
                'verbose_name_plural': 'Transitionen',
                'ordering': ['reihenfolge', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AntrVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('kommentar', models.CharField(blank=True, max_length=200)),
                ('snapshot_json', models.JSONField(verbose_name='Snapshot')),
                ('version_nr', models.PositiveIntegerField(verbose_name='Version')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antr_pfad_versionen', to=settings.AUTH_USER_MODEL)),
                ('pfad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versionen', to='formulare.antrpfad')),
            ],
            options={
                'verbose_name': 'Pfad-Version',
                'verbose_name_plural': 'Pfad-Versionen',
                'ordering': ['-version_nr'],
                'unique_together': {('pfad', 'version_nr')},
            },
        ),
    ]
