# Generated by Django 5.2.12 on 2026-04-05 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        # workflow_template_id column already exists in DB (added manually) –
        # update Django state only, skip the actual ALTER TABLE.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='antrpfad',
                    name='workflow_template',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Dieser Workflow startet automatisch wenn der Antrag abgeschlossen wird.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='verknuepfte_pfade',
                        to='workflow.workflowtemplate',
                        verbose_name='Workflow nach Abschluss',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='antrsitzung',
            name='tracking_token',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Token fuer oeffentliche Vorgangs-Verfolgung ohne Login',
                max_length=64,
                verbose_name='Tracking-Token',
            ),
        ),
    ]
