# Generated by Django 5.2.13 on 2026-04-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0004_antrpfad_leika_schluessel'),
    ]

    operations = [
        migrations.AddField(
            model_name='antrschritt',
            name='loop_bezeichnung',
            field=models.CharField(blank=True, default='', help_text="z.B. 'Kind' → '1. Kind', '2. Kind' in der PDF-Ausgabe", max_length=100, verbose_name='Loop-Bezeichnung'),
        ),
        migrations.AddField(
            model_name='antrschritt',
            name='loop_titel_feld',
            field=models.CharField(blank=True, default='', help_text="Feld-ID dessen Wert als Untertitel erscheint, z.B. 'vorname'", max_length=100, verbose_name='Loop-Titelfeld'),
        ),
    ]
