# Generated by Django 5.2.13 on 2026-04-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0008_antrsitzung_pfad_version_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='antrschritt',
            name='loop_max',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximale Anzahl Iterationen (0 = unbegrenzt)', verbose_name='Loop-Maximum'),
        ),
    ]
