# Generated by Django 5.2.13 on 2026-04-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0009_loop_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='antrsitzung',
            name='bestaetigt_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bestätigt am'),
        ),
        migrations.AddField(
            model_name='antrsitzung',
            name='bestaetigt_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP bei Bestätigung'),
        ),
        migrations.AddField(
            model_name='antrsitzung',
            name='bestaetigung_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Bestätigungs-E-Mail'),
        ),
        migrations.AddField(
            model_name='antrsitzung',
            name='bestaetigung_signatur',
            field=models.TextField(blank=True, default='', verbose_name='Unterschrift (SVG/base64)'),
        ),
        migrations.AddField(
            model_name='antrsitzung',
            name='bestaetigung_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Bestätigungs-Token'),
        ),
    ]
