# Generated by Django 5.2.13 on 2026-04-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0010_bestaetigung_felder'),
    ]

    operations = [
        migrations.AddField(
            model_name='antrsitzung',
            name='bestaetigung_firmenname',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Firmenname (Bestätigung)'),
        ),
        migrations.AddField(
            model_name='antrsitzung',
            name='bestaetigung_kontaktname',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Unterzeichner Name (Bestätigung)'),
        ),
        migrations.AddField(
            model_name='antrsitzung',
            name='bestaetigung_telefon',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Telefon Rückfrage (Bestätigung)'),
        ),
    ]
