# Generated by Django 6.0.3 on 2026-04-02 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktion', models.CharField(choices=[('login', 'Anmeldung'), ('logout', 'Abmeldung'), ('login_fehlgeschlagen', 'Anmeldung fehlgeschlagen'), ('erstellt', 'Objekt erstellt'), ('geaendert', 'Objekt geaendert'), ('geloescht', 'Objekt geloescht'), ('zugriff', 'Zugriff'), ('export', 'Export'), ('import', 'Import'), ('passwort_geaendert', 'Passwort geaendert')], max_length=30, verbose_name='Aktion')),
                ('app', models.CharField(blank=True, max_length=50, verbose_name='App')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('objekt_id', models.CharField(blank=True, max_length=50, verbose_name='Objekt-ID')),
                ('objekt_typ', models.CharField(blank=True, max_length=100, verbose_name='Objekt-Typ')),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Audit-Log',
                'verbose_name_plural': 'Audit-Logs',
                'ordering': ['-zeitpunkt'],
            },
        ),
        migrations.CreateModel(
            name='Benutzerprofil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abteilung', models.CharField(blank=True, max_length=200, verbose_name='Abteilung')),
                ('sprache', models.CharField(choices=[('de', 'Deutsch'), ('en', 'Englisch')], default='de', max_length=5, verbose_name='Sprache')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Benutzerprofil',
                'verbose_name_plural': 'Benutzerprofile',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
