# Generated by Django 5.2.12 on 2026-04-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('zusammenfassung', models.TextField(verbose_name='Zusammenfassung')),
                ('details', models.TextField(blank=True, verbose_name='Details / Technischer Hintergrund')),
                ('status', models.CharField(choices=[('idee', 'Idee / Vision'), ('verfuegbar', 'Standard heute verfuegbar'), ('geplant', 'Geplant'), ('entwicklung', 'In Entwicklung'), ('umgesetzt', 'Umgesetzt')], default='idee', max_length=20, verbose_name='Status')),
                ('kategorie', models.CharField(choices=[('interop', 'Interoperabilitaet / G2G'), ('sicherheit', 'Sicherheit / Compliance'), ('buerger', 'Buergerportal'), ('ki', 'KI / Automatisierung'), ('workflow', 'Workflow / Prozesse'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=20, verbose_name='Kategorie')),
                ('standard', models.CharField(blank=True, max_length=200, verbose_name='Relevanter Standard / Gesetz')),
                ('link_url', models.URLField(blank=True, verbose_name='Link (Dokumentation / Spec)')),
                ('link_label', models.CharField(blank=True, max_length=100, verbose_name='Link-Beschriftung')),
                ('sortierung', models.IntegerField(default=0, verbose_name='Sortierung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Roadmap-Eintrag',
                'verbose_name_plural': 'Roadmap',
                'ordering': ['sortierung', '-erstellt_am'],
            },
        ),
        migrations.AddField(
            model_name='benutzerprofil',
            name='email_bei_abschluss',
            field=models.BooleanField(default=True, help_text='Benachrichtigung wenn ein Workflow abgeschlossen wurde.', verbose_name='E-Mail bei Abschluss'),
        ),
        migrations.AddField(
            model_name='benutzerprofil',
            name='email_bei_faelligkeit',
            field=models.BooleanField(default=True, help_text='Erinnerung wenn eine Aufgabe überfällig ist.', verbose_name='E-Mail bei Fälligkeit'),
        ),
        migrations.AddField(
            model_name='benutzerprofil',
            name='email_bei_neuer_aufgabe',
            field=models.BooleanField(default=True, help_text='Benachrichtigung wenn eine neue Workflow-Aufgabe zugewiesen wird.', verbose_name='E-Mail bei neuer Aufgabe'),
        ),
    ]
