# Generated by Django 5.2.12 on 2026-04-06 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokumente', '0001_initial'),
        ('kommunikation', '0001_initial'),
        ('korrespondenz', '0005_briefvorgang_bearbeiter_signiert_am_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lfd_nr', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Tagebuch-Nr.')),
                ('datum', models.DateField(default=django.utils.timezone.now, verbose_name='Datum')),
                ('richtung', models.CharField(choices=[('eingang', 'Eingang'), ('ausgang', 'Ausgang')], max_length=10, verbose_name='Richtung')),
                ('typ', models.CharField(choices=[('brief', 'Brief'), ('email', 'E-Mail'), ('fax', 'Fax'), ('paket', 'Paket / Einschreiben'), ('intern', 'Interne Post'), ('sonstiges', 'Sonstiges')], default='brief', max_length=20, verbose_name='Typ')),
                ('absender_empfaenger', models.CharField(max_length=300, verbose_name='Absender / Empfaenger')),
                ('betreff', models.CharField(max_length=500, verbose_name='Betreff')),
                ('vorgang_bezug', models.CharField(blank=True, max_length=200, verbose_name='Vorgangsbezug / Aktenzeichen')),
                ('notiz', models.TextField(blank=True, verbose_name='Interne Notiz')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='Geaendert am')),
                ('briefvorgang', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posteintrag', to='korrespondenz.briefvorgang', verbose_name='Briefvorgang')),
                ('dokument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posteintraege', to='dokumente.dokument', verbose_name='Dokument')),
                ('eingehende_email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posteintrag', to='kommunikation.eingehendeemail', verbose_name='Eingehende E-Mail')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posteintraege', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Posteintrag',
                'verbose_name_plural': 'Postbuch',
                'ordering': ['-datum', '-lfd_nr'],
                'indexes': [models.Index(fields=['datum'], name='post_postei_datum_695f07_idx'), models.Index(fields=['richtung', 'datum'], name='post_postei_richtun_25251e_idx')],
            },
        ),
    ]
