# Generated by Django 5.2.12 on 2026-04-06 11:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('workflow', '0002_alter_workflowstep_aktion_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerteilEmpfaenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Empfaenger-Bezeichnung')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail-Adresse')),
                ('typ', models.CharField(choices=[('email', 'E-Mail'), ('brief', 'Brief / manuell')], default='email', max_length=10)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ausstehend', 'Ausstehend'), ('versendet', 'Versendet'), ('bestaetigt', 'Bestaetigt'), ('manuell', 'Manuell erledigt')], default='ausstehend', max_length=20)),
                ('versendet_am', models.DateTimeField(blank=True, null=True, verbose_name='Versendet am')),
                ('bestaetigt_am', models.DateTimeField(blank=True, null=True, verbose_name='Bestaetigt am')),
                ('bestaetigung_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP bei Bestaetigung')),
                ('notiz', models.TextField(blank=True, verbose_name='Notiz')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('workflow_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verteiler', to='workflow.workflowtask', verbose_name='Workflow-Task')),
            ],
            options={
                'verbose_name': 'Verteiler-Empfaenger',
                'verbose_name_plural': 'Verteiler-Empfaenger',
                'ordering': ['erstellt_am'],
            },
        ),
    ]
