# Generated by Django 5.2.12 on 2026-04-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_verteilempfaenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name / Bezeichnung')),
                ('typ', models.CharField(choices=[('behoerde', 'Behörde'), ('polizei', 'Polizei / Strafverfolgung'), ('gericht', 'Gericht'), ('gemeinde', 'Gemeinde / Stadt'), ('sonstige', 'Sonstige Institution')], default='behoerde', max_length=20, verbose_name='Typ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='Fax')),
                ('strasse', models.CharField(blank=True, max_length=200, verbose_name='Straße / Hausnummer')),
                ('plz', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('ort', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('notiz', models.TextField(blank=True, verbose_name='Interne Notiz')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisationsverzeichnis',
                'ordering': ['name'],
            },
        ),
    ]
