# Generated by Django 5.2.12 on 2026-04-02 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EingehendeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absender_email', models.EmailField(max_length=254, verbose_name='Absender (E-Mail)')),
                ('absender_name', models.CharField(blank=True, max_length=255, verbose_name='Absender (Name)')),
                ('betreff', models.CharField(blank=True, max_length=500, verbose_name='Betreff')),
                ('empfangen_am', models.DateTimeField(verbose_name='Empfangen am')),
                ('empfaenger_email', models.EmailField(blank=True, max_length=254, verbose_name='Empfaenger (E-Mail)')),
                ('importiert_am', models.DateTimeField(auto_now_add=True, verbose_name='Importiert am')),
                ('inhalt_html', models.TextField(blank=True, verbose_name='Inhalt (HTML)')),
                ('inhalt_text', models.TextField(blank=True, verbose_name='Inhalt (Text)')),
                ('message_id', models.CharField(help_text='RFC 2822 Message-ID zur Deduplizierung', max_length=500, unique=True, verbose_name='Message-ID')),
                ('notiz', models.TextField(blank=True, verbose_name='Interne Notiz')),
                ('status', models.CharField(choices=[('neu', 'Neu'), ('gelesen', 'Gelesen'), ('archiviert', 'Archiviert'), ('zugewiesen', 'Zugewiesen')], default='neu', max_length=20, verbose_name='Status')),
                ('zugewiesen_an', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zugewiesene_emails', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
            ],
            options={
                'verbose_name': 'Eingehende E-Mail',
                'verbose_name_plural': 'Eingehende E-Mails',
                'ordering': ['-empfangen_am'],
            },
        ),
        migrations.CreateModel(
            name='EmailAnhang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateiname', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('dateityp', models.CharField(blank=True, max_length=100, verbose_name='MIME-Typ')),
                ('groesse_bytes', models.BigIntegerField(default=0, verbose_name='Groesse (Bytes)')),
                ('inhalt', models.BinaryField(verbose_name='Dateiinhalt')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anhaenge', to='kommunikation.eingehendeemail', verbose_name='E-Mail')),
            ],
            options={
                'verbose_name': 'E-Mail-Anhang',
                'verbose_name_plural': 'E-Mail-Anhaenge',
                'ordering': ['dateiname'],
            },
        ),
        migrations.CreateModel(
            name='Benachrichtigung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('gelesen', models.BooleanField(default=False, verbose_name='Gelesen')),
                ('gelesen_am', models.DateTimeField(blank=True, null=True, verbose_name='Gelesen am')),
                ('link', models.CharField(blank=True, help_text='URL-Pfad zum verknuepften Objekt', max_length=500, verbose_name='Link')),
                ('nachricht', models.TextField(verbose_name='Nachricht')),
                ('titel', models.CharField(max_length=255, verbose_name='Titel')),
                ('typ', models.CharField(choices=[('info', 'Information'), ('warnung', 'Warnung'), ('aufgabe', 'Aufgabe'), ('email', 'Neue E-Mail')], default='info', max_length=20, verbose_name='Typ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benachrichtigungen', to=settings.AUTH_USER_MODEL, verbose_name='Empfaenger')),
            ],
            options={
                'verbose_name': 'Benachrichtigung',
                'verbose_name_plural': 'Benachrichtigungen',
                'ordering': ['-erstellt_am'],
                'indexes': [models.Index(fields=['user', 'gelesen', 'erstellt_am'], name='kommunikati_user_id_5bef0a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='eingehendeemail',
            index=models.Index(fields=['status', 'empfangen_am'], name='kommunikati_status_dffd9e_idx'),
        ),
        migrations.AddIndex(
            model_name='eingehendeemail',
            index=models.Index(fields=['absender_email'], name='kommunikati_absende_220465_idx'),
        ),
    ]
