# Generated by Django 5.2.12 on 2026-04-02 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('object_id', models.PositiveIntegerField()),
                ('fortschritt', models.IntegerField(default=0, verbose_name='Fortschritt (%)')),
                ('gestartet_am', models.DateTimeField(auto_now_add=True, verbose_name='Gestartet am')),
                ('status', models.CharField(choices=[('laufend', 'Laufend'), ('abgeschlossen', 'Abgeschlossen'), ('abgebrochen', 'Abgebrochen'), ('pausiert', 'Pausiert')], default='laufend', max_length=50, verbose_name='Status')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('gestartet_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestartete_workflow_instanzen', to=settings.AUTH_USER_MODEL, verbose_name='Gestartet von')),
            ],
            options={
                'verbose_name': 'Workflow-Instanz',
                'verbose_name_plural': 'Workflow-Instanzen',
                'ordering': ['-gestartet_am'],
            },
        ),
        migrations.CreateModel(
            name='ProzessAntrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('ausloeser_detail', models.TextField(blank=True, verbose_name='Genauere Beschreibung des Ausloesers')),
                ('ausloeser_typ', models.CharField(choices=[('manuell', 'Manuell (Benutzer startet selbst)'), ('formular', 'Formular-Einreichung'), ('zeitgesteuert', 'Zeitgesteuert'), ('sonstiges', 'Sonstiges')], default='manuell', max_length=20, verbose_name='Wie wird der Prozess ausgeloest?')),
                ('bemerkungen', models.TextField(blank=True, verbose_name='Zusaetzliche Bemerkungen')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Eingereicht am')),
                ('name', models.CharField(max_length=200, verbose_name='Name des Prozesses')),
                ('pdf_benoetigt', models.BooleanField(default=False, verbose_name='Soll am Ende ein PDF erzeugt werden?')),
                ('schritte', models.JSONField(default=list, verbose_name='Prozessschritte')),
                ('status', models.CharField(choices=[('eingereicht', 'Eingereicht'), ('in_pruefung', 'In Pruefung'), ('in_umsetzung', 'In Umsetzung'), ('umgesetzt', 'Umgesetzt'), ('abgelehnt', 'Abgelehnt')], default='eingereicht', max_length=20, verbose_name='Status')),
                ('team_benoetigt', models.BooleanField(default=False, verbose_name='Wird ein Team benoetigt?')),
                ('team_vorschlag', models.TextField(blank=True, verbose_name='Team-Vorschlag')),
                ('ziel', models.TextField(verbose_name='Ziel des Prozesses')),
                ('antragsteller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prozessantraege', to=settings.AUTH_USER_MODEL, verbose_name='Antragsteller')),
                ('workflow_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prozessantraege', to='workflow.workflowinstance', verbose_name='Workflow-Instanz')),
            ],
            options={
                'verbose_name': 'Prozessantrag',
                'verbose_name_plural': 'Prozessantraege',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_config', models.JSONField(blank=True, null=True, verbose_name='Automatische Aktions-Konfiguration')),
                ('aktion_typ', models.CharField(choices=[('genehmigen', 'Genehmigen'), ('pruefen', 'Pruefen'), ('informieren', 'Informieren'), ('bearbeiten', 'Bearbeiten'), ('entscheiden', 'Entscheiden'), ('benachrichtigen', 'Benachrichtigung senden'), ('email', 'Email senden'), ('webhook', 'Webhook aufrufen')], default='pruefen', max_length=50, verbose_name='Aktionstyp')),
                ('beschreibung', models.TextField(blank=True, help_text='Detaillierte Anweisungen fuer den Bearbeiter', verbose_name='Beschreibung')),
                ('bedingung_feld', models.CharField(blank=True, max_length=100, verbose_name='Bedingungsfeld')),
                ('bedingung_operator', models.CharField(blank=True, choices=[('>', 'Groesser als'), ('<', 'Kleiner als'), ('==', 'Gleich'), ('!=', 'Ungleich'), ('>=', 'Groesser oder gleich'), ('<=', 'Kleiner oder gleich')], max_length=10, verbose_name='Bedingungsoperator')),
                ('bedingung_wert', models.CharField(blank=True, max_length=100, verbose_name='Bedingungswert')),
                ('eskalation_nach_tagen', models.IntegerField(default=0, help_text='0 = keine Eskalation', verbose_name='Eskalation nach (Tage)')),
                ('frist_tage', models.IntegerField(default=3, verbose_name='Frist (Tage)')),
                ('ist_parallel', models.BooleanField(default=False, help_text='Wird gleichzeitig mit naechstem Schritt ausgefuehrt', verbose_name='Parallel')),
                ('node_id', models.CharField(blank=True, help_text='Eindeutige ID im Editor-Graph', max_length=50, verbose_name='Node-ID')),
                ('pos_x', models.FloatField(default=200, verbose_name='Position X')),
                ('pos_y', models.FloatField(default=200, verbose_name='Position Y')),
                ('reihenfolge', models.IntegerField(default=1, help_text='Fuer lineare Workflows – bei Graph-Workflows durch Transitions ersetzt', verbose_name='Reihenfolge')),
                ('schritt_typ', models.CharField(choices=[('task', 'Benutzer-Task (Standard)'), ('auto', 'Automatische Aktion'), ('decision', 'Entscheidungs-Node (mehrere Ausgaenge)')], default='task', max_length=20, verbose_name='Schritt-Typ')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('zustaendig_rolle', models.CharField(choices=[('gruppe', 'Gruppe (alle Mitglieder sehen den Task)'), ('spezifischer_user', 'Spezifischer Benutzer'), ('antragsteller', 'Antragsteller selbst')], default='gruppe', max_length=50, verbose_name='Zustaendige Rolle')),
                ('eskalation_an_gruppe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eskalations_schritte', to='auth.group', verbose_name='Eskalation an Gruppe')),
                ('zustaendig_gruppe', models.ForeignKey(blank=True, help_text='Alle Mitglieder der Gruppe sehen und koennen den Task bearbeiten', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_schritte', to='auth.group', verbose_name='Zustaendige Gruppe')),
                ('zustaendig_user', models.ForeignKey(blank=True, help_text="Nur bei Rolle 'Spezifischer Benutzer'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zustaendige_workflow_schritte', to=settings.AUTH_USER_MODEL, verbose_name='Spezifischer Benutzer')),
            ],
            options={
                'verbose_name': 'Workflow-Schritt',
                'verbose_name_plural': 'Workflow-Schritte',
                'ordering': ['template', 'reihenfolge'],
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='aktueller_schritt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktive_instanzen', to='workflow.workflowstep', verbose_name='Aktueller Schritt'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('ist_aktiv', models.BooleanField(default=True, help_text='Inaktive Templates koennen nicht gestartet werden', verbose_name='Aktiv')),
                ('ist_graph_workflow', models.BooleanField(default=True, help_text='Wenn True, werden Transitions verwendet statt Reihenfolge', verbose_name='Graph-basierter Workflow')),
                ('kategorie', models.CharField(choices=[('genehmigung', 'Genehmigung'), ('pruefung', 'Pruefung'), ('information', 'Information'), ('bearbeitung', 'Bearbeitung')], default='genehmigung', max_length=50, verbose_name='Kategorie')),
                ('name', models.CharField(help_text='Name des Workflows (z.B. Urlaubsantrag-Genehmigung)', max_length=200, verbose_name='Name')),
                ('trigger_event', models.CharField(blank=True, help_text='Event das diesen Workflow automatisch startet', max_length=100, verbose_name='Trigger-Event')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Workflow-Template',
                'verbose_name_plural': 'Workflow-Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schritte', to='workflow.workflowtemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instanzen', to='workflow.workflowtemplate', verbose_name='Template'),
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedingung_entscheidung', models.CharField(blank=True, choices=[('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('weitergeleitet', 'Weitergeleitet'), ('rueckfrage', 'Rueckfrage'), ('zurueck_antragsteller', 'Zurueck an Antragsteller')], max_length=30, null=True, verbose_name='Erwartete Entscheidung')),
                ('bedingung_feld', models.CharField(blank=True, max_length=100, verbose_name='Bedingungsfeld')),
                ('bedingung_operator', models.CharField(blank=True, choices=[('==', 'Gleich'), ('!=', 'Ungleich'), ('>', 'Groesser als'), ('<', 'Kleiner als'), ('>=', 'Groesser oder gleich'), ('<=', 'Kleiner oder gleich'), ('in', 'Enthalten in')], max_length=10, verbose_name='Operator')),
                ('bedingung_typ', models.CharField(choices=[('immer', 'Immer (keine Bedingung)'), ('entscheidung', 'Basierend auf Task-Entscheidung'), ('feld_wert', 'Basierend auf Feld-Wert')], default='immer', max_length=20, verbose_name='Bedingungstyp')),
                ('bedingung_wert', models.CharField(blank=True, max_length=255, verbose_name='Bedingungswert')),
                ('label', models.CharField(blank=True, help_text="z.B. 'genehmigt', 'abgelehnt'", max_length=50, verbose_name='Beschriftung')),
                ('prioritaet', models.IntegerField(default=1, verbose_name='Prioritaet')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflowtemplate', verbose_name='Template')),
                ('von_schritt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausgaenge', to='workflow.workflowstep', verbose_name='Von Schritt')),
                ('zu_schritt', models.ForeignKey(blank=True, help_text='NULL = Ende-Node', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eingaenge', to='workflow.workflowstep', verbose_name='Zu Schritt')),
            ],
            options={
                'verbose_name': 'Workflow-Uebergang',
                'verbose_name_plural': 'Workflow-Uebergaenge',
                'ordering': ['prioritaet'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antragsteller_pfad', models.CharField(default='erstellt_von', help_text="Punkt-getrennter Attributpfad zum User-Objekt (z.B. 'erstellt_von' oder 'user')", max_length=200, verbose_name='Antragsteller-Pfad')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('ist_aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('trigger_auf', models.CharField(choices=[('erstellt', 'Neu erstellt'), ('aktualisiert', 'Aktualisiert')], default='erstellt', max_length=20, verbose_name='Ausloesen bei')),
                ('trigger_event', models.CharField(help_text='Eindeutiger Schluessel (muss mit WorkflowTemplate.trigger_event uebereinstimmen)', max_length=100, unique=True, verbose_name='Trigger-Event-Key')),
                ('workflow_instance_feld', models.CharField(default='workflow_instance', max_length=100, verbose_name='Workflow-Instance-Feld')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Django-Model')),
            ],
            options={
                'verbose_name': 'Workflow-Trigger',
                'verbose_name_plural': 'Workflow-Trigger',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_am', models.DateTimeField(blank=True, null=True, verbose_name='Geclaimed am')),
                ('entscheidung', models.CharField(blank=True, choices=[('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('weitergeleitet', 'Weitergeleitet'), ('rueckfrage', 'Rueckfrage'), ('zurueck_antragsteller', 'Zurueck an Antragsteller')], max_length=50, verbose_name='Entscheidung')),
                ('erledigt_am', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('frist', models.DateTimeField(verbose_name='Frist')),
                ('gestartet_am', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet am')),
                ('kommentar', models.TextField(blank=True, verbose_name='Kommentar')),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt'), ('uebersprungen', 'Uebersprungen'), ('eskaliert', 'Eskaliert')], default='offen', max_length=50, verbose_name='Status')),
                ('claimed_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Geclaimed von')),
                ('erledigt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erledigte_workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Erledigt von')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.workflowinstance', verbose_name='Workflow-Instanz')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.workflowstep', verbose_name='Workflow-Schritt')),
                ('zugewiesen_an_gruppe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_tasks', to='auth.group', verbose_name='Zugewiesen an Gruppe')),
                ('zugewiesen_an_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an Benutzer')),
            ],
            options={
                'verbose_name': 'Workflow-Task',
                'verbose_name_plural': 'Workflow-Tasks',
                'ordering': ['frist', '-erstellt_am'],
                'indexes': [models.Index(fields=['status', 'frist'], name='workflow_wo_status_abef98_idx'), models.Index(fields=['zugewiesen_an_gruppe', 'status'], name='workflow_wo_zugewie_3bf808_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='workflow_wo_content_5cb705_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status', 'gestartet_am'], name='workflow_wo_status_824408_idx'),
        ),
    ]
