# Generated by Django 5.2.12 on 2026-04-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='aktion_typ',
            field=models.CharField(choices=[('genehmigen', 'Genehmigen'), ('pruefen', 'Pruefen'), ('informieren', 'Informieren'), ('bearbeiten', 'Bearbeiten'), ('entscheiden', 'Entscheiden'), ('benachrichtigen', 'Benachrichtigung senden'), ('email', 'Email senden'), ('webhook', 'Webhook aufrufen'), ('verteilen', 'Verteiler / Akte versenden')], default='pruefen', max_length=50, verbose_name='Aktionstyp'),
        ),
    ]
