# Generated by Django 5.2.12 on 2026-04-02 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farbe', models.CharField(default='#6c757d', help_text='z.B. #1a4d2e', max_length=7, verbose_name='Farbe (Hex)')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Dokumenttag',
                'verbose_name_plural': 'Dokumenttags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DokumentKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('sortierung', models.IntegerField(default=0, verbose_name='Sortierung')),
                ('elternkategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unterkategorien', to='dokumente.dokumentkategorie', verbose_name='Elternkategorie')),
            ],
            options={
                'verbose_name': 'Dokumentkategorie',
                'verbose_name_plural': 'Dokumentkategorien',
                'ordering': ['sortierung', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateiname', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('dateityp', models.CharField(blank=True, max_length=100, verbose_name='Dateityp (MIME)')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='Geaendert am')),
                ('groesse_bytes', models.BigIntegerField(default=0, verbose_name='Groesse (Bytes)')),
                ('gueltig_bis', models.DateField(blank=True, null=True, verbose_name='Gueltig bis')),
                ('inhalt', models.BinaryField(verbose_name='Dateiinhalt')),
                ('titel', models.CharField(max_length=255, verbose_name='Titel')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('wopi_token', models.CharField(blank=True, max_length=64, verbose_name='WOPI-Token')),
                ('wopi_token_ablauf', models.DateTimeField(blank=True, null=True, verbose_name='WOPI-Token Ablauf')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_dokumente', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('kategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumente', to='dokumente.dokumentkategorie', verbose_name='Kategorie')),
                ('tags', models.ManyToManyField(blank=True, related_name='dokumente', to='dokumente.dokumenttag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-geaendert_am'],
            },
        ),
        migrations.CreateModel(
            name='DokumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('groesse_bytes', models.BigIntegerField(default=0, verbose_name='Groesse (Bytes)')),
                ('inhalt', models.BinaryField(verbose_name='Dateiinhalt')),
                ('kommentar', models.CharField(blank=True, max_length=255, verbose_name='Kommentar')),
                ('version_nr', models.IntegerField(verbose_name='Versionsnummer')),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versionen', to='dokumente.dokument', verbose_name='Dokument')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Dokumentversion',
                'verbose_name_plural': 'Dokumentversionen',
                'ordering': ['-version_nr'],
            },
        ),
        migrations.CreateModel(
            name='ZugriffsProtokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktion', models.CharField(choices=[('download', 'Heruntergeladen'), ('vorschau', 'Vorschau'), ('erstellt', 'Erstellt'), ('geaendert', 'Geaendert'), ('geloescht', 'Geloescht'), ('collabora_bearbeitet', 'In Collabora bearbeitet'), ('version_wiederhergestellt', 'Version wiederhergestellt'), ('hochgeladen', 'Hochgeladen')], max_length=30, verbose_name='Aktion')),
                ('dokument_titel', models.CharField(help_text='Sicherungskopie fuer geloeschte Dokumente', max_length=255, verbose_name='Dokumenttitel')),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('notiz', models.CharField(blank=True, max_length=255, verbose_name='Notiz')),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('dokument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protokolle', to='dokumente.dokument', verbose_name='Dokument')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Zugriffsprotokoll',
                'verbose_name_plural': 'Zugriffsprotokolle',
                'ordering': ['-zeitpunkt'],
            },
        ),
        migrations.AddIndex(
            model_name='dokument',
            index=models.Index(fields=['dateiname'], name='dokumente_d_dateina_383fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='dokument',
            index=models.Index(fields=['erstellt_von', 'erstellt_am'], name='dokumente_d_erstell_6386a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dokumentversion',
            unique_together={('dokument', 'version_nr')},
        ),
    ]
